version: 0.2

phases:
  pre_build:
    commands:
      - . ./populate_build_env.sh;
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region ${AWS_REGION})
  build:
    commands:
      - echo "Build started on $(date)"
      - echo "Building the Docker image ${IMAGE_REPO_NAME}:${IMAGE_TAG} ..."
      - docker build -t ${IMAGE_REPO_NAME}:${IMAGE_TAG} .
      - docker tag ${IMAGE_REPO_NAME}:${IMAGE_TAG} ${CODEBUILD_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${IMAGE_REPO_NAME}:${IMAGE_TAG}      
  post_build:
    commands:
      - chmod ugo+x ./ensure_build_succeeding.sh; ./ensure_build_succeeding.sh
      - echo "Build completed on $(date)"
      - echo "Pushing the Docker image to ${CODEBUILD_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${IMAGE_REPO_NAME}:${IMAGE_TAG} ..."
      - docker push ${CODEBUILD_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${IMAGE_REPO_NAME}:${IMAGE_TAG}
      - printf '[{"name":"http-sink","imageUri":"%s"}]' ${CODEBUILD_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${IMAGE_REPO_NAME}:${IMAGE_TAG} > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
